production:
  adapter: postgresql
  encoding: unicode
  host: postgresql6.locum.ru
  database: nerrey_nerrey80
  username: nerrey_nerrey80
  password: Aaa14156

development:
  adapter: postgresql
  encoding: unicode
  host: postgresql6.locum.ru
  database: nerrey_nerrey80
  username: nerrey_nerrey80
  password: Aaa14156

test:
  adapter: postgresql
  encoding: unicode
  host: postgresql6.locum.ru
  database: nerrey_nerrey80
  username: nerrey_nerrey80
  password: Aaa14156